#!/usr/bin/env node
// Publish the OBS source files into the existing GitHub Pages directory.
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');

const root = path.resolve(__dirname, '..');
const output = path.join(root, 'docs', 'obs');
const check = process.argv.includes('--check');
const colors = [
  ['agouti', 'アグーチ', 'Agouti'], ['sand', 'サンド', 'Sand'],
  ['yellow_sand', 'イエローサンド', 'Yellow Sand'], ['cream', 'クリーム', 'Cream'],
  ['white', 'ホワイト', 'White'], ['black', 'ブラック', 'Black'],
  ['blue', 'ブルー（グレー）', 'Blue (Gray)'], ['chocolate', 'チョコレート', 'Chocolate'],
  ['lilac', 'ライラック', 'Lilac'], ['violet', 'バイオレット', 'Violet'],
  ['agouti_pied', 'アグーチパイド', 'Agouti Pied'], ['sand_pied', 'サンドパイド', 'Sand Pied'],
  ['blue_pied', 'ブルーパイド', 'Blue Pied'], ['violet_pied', 'バイオレットパイド', 'Violet Pied'],
  ['cream_pied', 'クリームパイド', 'Cream Pied'], ['black_pied', 'ブラックパイド', 'Black Pied'],
];
const motions = [
  ['a-bottom-pop', '下からぴょこ', 'Pop up'],
  ['b-side-peek', '端からのぞく', 'Peek from the side'],
  ['c-center-hop', '跳び込む', 'Hop in'],
];
const species = [{ id: 'degu', name: { ja: 'デグー', en: 'Degu' } }];
const variants = colors.map(([id, ja, en]) => {
  const image = `../assets/colors/${id}.png`;
  assert.ok(fs.existsSync(path.join(root, 'docs', 'assets', 'colors', `${id}.png`)), `Missing image: ${id}`);
  return {
    id, species: 'degu', name: { ja, en }, image,
    motions: motions.map(([motion, motionJa, motionEn]) => {
      const file = `${id}-${motion}.webm`;
      assert.ok(fs.existsSync(path.join(root, 'assets', 'videos', file)), `Missing original video: ${file}`);
      assert.ok(fs.existsSync(path.join(root, 'docs', 'assets', 'obs-videos', file)), `Missing published video: ${file}`);
      return { id: motion, name: { ja: motionJa, en: motionEn }, video: `../assets/obs-videos/${file}` };
    }),
  };
});
assert.equal(variants.length, 16);
assert.equal(variants.reduce((count, item) => count + item.motions.length, 0), 48);

function files(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    if (entry.isDirectory()) return files(path.join(dir, entry.name)).map((file) => path.join(entry.name, file));
    assert.ok(entry.isFile(), `Unsupported source entry: ${entry.name}`);
    return [entry.name];
  });
}
function publish(src, dest) {
  if (check) {
    assert.ok(fs.existsSync(dest), `Missing generated file: ${dest}`);
    assert.deepEqual(fs.readFileSync(dest), fs.readFileSync(src), `Outdated generated file: ${dest}`);
  } else {
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.copyFileSync(src, dest);
  }
}

const web = path.join(root, 'web', 'obs');
const shared = path.join(root, 'shared', 'overlay');
const webFiles = files(web);
const sharedFiles = files(shared);
const expected = [...webFiles, ...sharedFiles.map((file) => path.join('shared', 'overlay', file)), 'catalog.mjs'].sort();
if (check) assert.deepEqual(files(output).sort(), expected, 'Generated OBS file list differs from source');
else fs.rmSync(output, { recursive: true, force: true });
for (const file of webFiles) publish(path.join(web, file), path.join(output, file));
for (const file of sharedFiles) publish(path.join(shared, file), path.join(output, 'shared', 'overlay', file));
const catalog = `// Generated by scripts/build-obs-web.js. Do not edit.\nexport const species = ${JSON.stringify(species, null, 2)};\nexport const variants = ${JSON.stringify(variants, null, 2)};\n`;
const catalogFile = path.join(output, 'catalog.mjs');
if (check) assert.equal(fs.readFileSync(catalogFile, 'utf8'), catalog);
else fs.writeFileSync(catalogFile, catalog);
process.stdout.write(`OBS web ${check ? 'checked' : 'built'}: 16 coats, 48 motions.\n`);
